### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xyproto** [hikiko/gl4#1]
Hi,

I wish to include a modified version of this program as an OpenGL example in [cxx](https://github.com/xyproto/cxx).

Which license is `gl4` released under?

Best regards,
Alexander F. Rødseth

**Comment by hikiko** [comment]
Hi, feel free to consider it public domain, I will update the README shortly to make it official. :)

**Comment by hikiko** [comment]
Done, I am closing this issue!

**Comment by xyproto** [comment]
Thank you!
